name: Fetch Overleaf PDF

on:
  schedule:
    - cron: "1 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download latest PDF
        run: |
          curl -L "https://www.overleaf.com/download/project/6a0366defdc17ed26a499c69/build/19e278c8cf1-03103b8aa6abbf36/output/output.pdf?compileGroup=standard&clsiserverid=clsi-pre-emp-c3d-d-f-kftm&enable_pdf_caching=true&popupDownload=true&editorId=0e402836-b0fa-435a-ab92-06143ddd2f96" -o AP2026.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
